### ISSUE TITLE
merge props which are not present in propsOrder

### ISSUE THREAD

**Issue by freakyjammer** [evalgo/evschema#5]
If propsOrder does not contain order for all props, remaining props get lost in current version. 
Append not ordered props to the end of orderedProps.

**Comment by cyball** [comment]
yes .. you should append the props in random order at the end of the ordered list of props

**Comment by freakyjammer** [comment]
fixed in commit b621a7cc1e5e5f5e12bc42d3c5f4b7c8d0ed0db7
